# Generated by Django 4.2.11 on 2024-04-22 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_alter_order_package_id_alter_product_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amazon_account',
        ),
        migrations.AddField(
            model_name='order',
            name='ups_account',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AmazonUser',
        ),
    ]
