# Generated by Django 5.0.4 on 2024-04-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ups_account',
            field=models.IntegerField(null=True),
        ),
    ]
